version: "3"
services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=khipo'
      - 'POSTGRES_PASSWORD=khipo'
      - 'POSTGRES_USER=khipo'
    ports:
      - '5432'
