spring:
  application:
    name: khipo-teste
  datasource:
    url: ${DB_HOSTNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: false
logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs:
    path: /doc/api-docs
  swagger-ui:
    path: /doc/documentation.html

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

